name: Build React Docker Image
on: push

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        uses: actions/checkout@v3
      - name: Investigate host
        run: |
          pwd
          ls -lart
