name: Build React Docker Image
on:
  push:
    branches: ["add_workflow"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Save version
        id: version
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))

      - name: Increase version
        run: npm version patch

      - name: Push new version
        run: git push

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag dan77uk/test:${{steps.version.outputs.tag}}

      - name: Push to Docker Hub
        run: docker push dan77uk/test:${{steps.version.outputs.tag}}
